platform :ios, '8.0'
inhibit_all_warnings!
target "Project" do
pod 'AFNetworking'
pod 'ActionSheetPicker-3.0'
pod 'MJRefresh'
# 等待框
pod 'MBProgressHUD'
# 堆栈
pod 'MLeaksFinder'
# 图片选择库
pod 'TZImagePickerController'
# 图像处理库
pod 'NYXImagesKit'
# json解析
pod 'MJExtension'
# 界面适配
pod 'Masonry'
pod 'SDWebImage'
# 富文本
pod 'YYText'
# 输入限制
pod 'InputKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
     end
   end
  end
end


# pod 'IQKeyboardManager'
# pod 'FMDB'
# pod 'JDStatusBarNotification'
# pod 'ReactiveObjC'
# pod 'OpenUDID'
# pod 'NJKWebViewProgress'
# pod 'SSZipArchive'
# pod 'BaiduMapKit'
# pod 'VRGCalendarView'

