platform :ios, '8.0'

target "Project" do
# pod 'IQKeyboardManager'
# pod 'FMDB'
# pod 'JDStatusBarNotification'
# pod 'ReactiveObjC'
pod 'ActionSheetPicker-3.0'
# pod 'VRGCalendarView'
pod 'MJRefresh'
# pod 'OpenUDID'
# pod 'NJKWebViewProgress'
# pod 'SSZipArchive'
# pod 'BaiduMapKit'
# 等待框
pod 'MBProgressHUD'
# 堆栈
pod 'MLeaksFinder'
# 图片选择库
pod 'TZImagePickerController'
# 图像处理库
pod 'NYXImagesKit'
# json解析
pod 'MJExtension'
# 界面适配
pod 'Masonry'
pod 'SDWebImage'
# 富文本
pod 'YYText'
# 输入限制
pod 'InputKit'
pod 'RDVTabBarController'

end
